<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>hsp3dx_sjis2utf8</AssemblyName>
    <RootNamespace>Hsp3Dx.Sjis2Utf8</RootNamespace>
  </PropertyGroup>

</Project>
