;============================================================
;  iron_dxlib_auto.as — Phase 5.3 自動生成 DxLib bindings
;  DO NOT EDIT — tools/hsp3dx_dxlib_gen/gen_dxlib_bindings.py で再生成
;  関数数: 1129
;============================================================
#ifndef __iron_dxlib_auto_as__
#define __iron_dxlib_auto_as__

#regcmd 9

#cmd dx_global_struct_initialize            $200
#cmd dx_is_init                             $201
#cmd dx_get_last_error_code                 $202
#cmd dx_get_last_error_message              $203
#cmd dx_set_always_run_flag                 $204
#cmd dx_wait_timer                          $205
#cmd dx_wait_key                            $206
#cmd dx_sleep_thread                        $207
#cmd dx_get_now_count                       $208
#cmd dx_get_rand                            $209
#cmd dx_s_rand                              $20a
#cmd dx_get_battery_life_percent            $20b
#cmd dx_get_clipboard_text                  $20c
#cmd dx_set_clipboard_text                  $20d
#cmd dx_log_file_add                        $20e
#cmd dx_log_file_tab_add                    $20f
#cmd dx_log_file_tab_sub                    $210
#cmd dx_error_log_add                       $211
#cmd dx_error_log_tab_add                   $212
#cmd dx_error_log_tab_sub                   $213
#cmd dx_set_use_time_stamp_flag             $214
#cmd dx_set_out_application_log_valid_flag  $215
#cmd dx_set_out_application_system_log_valid_flag $216
#cmd dx_set_application_log_file_name       $217
#cmd dx_set_application_log_save_directory  $218
#cmd dx_set_use_date_name_log_file          $219
#cmd dx_set_log_draw_out_flag               $21a
#cmd dx_get_log_draw_flag                   $21b
#cmd dx_set_log_font_size                   $21c
#cmd dx_set_log_font_handle                 $21d
#cmd dx_set_log_draw_area                   $21e
#cmd dx_puts_dx                             $21f
#cmd dx_cls_dx                              $220
#cmd dx_set_print_color_dx                  $221
#cmd dx_set_use_a_sync_load_flag            $222
#cmd dx_get_use_a_sync_load_flag            $223
#cmd dx_check_handle_a_sync_load            $224
#cmd dx_get_handle_a_sync_load_result       $225
#cmd dx_set_a_sync_load_finish_delete_flag  $226
#cmd dx_wait_handle_a_sync_load             $227
#cmd dx_wait_handle_a_sync_load_all         $228
#cmd dx_get_a_sync_load_num                 $229
#cmd dx_set_a_sync_load_thread_num          $22a
#cmd dx_set_mouse_disp_flag                 $22b
#cmd dx_set_mouse_disp_ignore_menu_flag     $22c
#cmd dx_get_mouse_wheel_rot_vol             $22d
#cmd dx_get_mouse_h_wheel_rot_vol           $22e
#cmd dx_get_touch_input_num                 $22f
#cmd dx_get_touch_input_log_num             $230
#cmd dx_clear_touch_input_log               $231
#cmd dx_get_touch_input_down_log_num        $232
#cmd dx_clear_touch_input_down_log          $233
#cmd dx_get_touch_input_up_log_num          $234
#cmd dx_clear_touch_input_up_log            $235
#cmd dx_dx_set_alloc_print_flag             $236
#cmd dx_dx_get_alloc_num                    $237
#cmd dx_dx_error_check_alloc                $238
#cmd dx_dx_set_alloc_size_out_flag          $239
#cmd dx_dx_set_alloc_memory_error_check_flag $23a
#cmd dx_get_use_char_code_format            $23b
#cmd dx_get_wchar_t_char_code_format        $23c
#cmd dx_strcmp_dx                           $23d
#cmd dx_stricmp_dx                          $23e
#cmd dx_strncmp_dx                          $23f
#cmd dx_strncmp2_dx                         $240
#cmd dx_strpncmp_dx                         $241
#cmd dx_strpncmp2_dx                        $242
#cmd dx_strstr2_dx                          $243
#cmd dx_strrstr2_dx                         $244
#cmd dx_atoi_dx                             $245
#cmd dx_process_net_message                 $246
#cmd dx_preparation_listen_net_work         $247
#cmd dx_preparation_listen_net_work_i_pv6   $248
#cmd dx_stop_listen_net_work                $249
#cmd dx_close_net_work                      $24a
#cmd dx_get_net_work_accept_state           $24b
#cmd dx_get_net_work_data_length            $24c
#cmd dx_get_net_work_send_data_length       $24d
#cmd dx_get_new_accept_net_work             $24e
#cmd dx_get_lost_net_work                   $24f
#cmd dx_set_connect_time_out_wait           $250
#cmd dx_set_use_dx_net_work_protocol        $251
#cmd dx_get_use_dx_net_work_protocol        $252
#cmd dx_set_use_dx_protocol                 $253
#cmd dx_get_use_dx_protocol                 $254
#cmd dx_set_net_work_close_after_lost_flag  $255
#cmd dx_get_net_work_close_after_lost_flag  $256
#cmd dx_net_work_recv_buffer_clear          $257
#cmd dx_make_udp_socket                     $258
#cmd dx_make_udp_socket_i_pv6               $259
#cmd dx_delete_udp_socket                   $25a
#cmd dx_check_net_work_recv_udp             $25b
#cmd dx_clear_input_char_buf                $25c
#cmd dx_get_one_char                        $25d
#cmd dx_get_one_char_wait                   $25e
#cmd dx_draw_ime_input_string               $25f
#cmd dx_draw_ime_input_extend_string        $260
#cmd dx_set_use_ime_flag                    $261
#cmd dx_get_use_ime_flag                    $262
#cmd dx_set_input_string_max_length_ime_sync $263
#cmd dx_set_ime_input_string_max_length     $264
#cmd dx_get_string_point                    $265
#cmd dx_get_string_point2                   $266
#cmd dx_get_string_length                   $267
#cmd dx_draw_obtains_box                    $268
#cmd dx_key_input_number                    $269
#cmd dx_get_ime_input_mode_str              $26a
#cmd dx_set_ime_input_string                $26b
#cmd dx_set_key_input_string_font           $26c
#cmd dx_draw_key_input_mode_string          $26d
#cmd dx_init_key_input                      $26e
#cmd dx_delete_key_input                    $26f
#cmd dx_set_active_key_input                $270
#cmd dx_get_active_key_input                $271
#cmd dx_check_key_input                     $272
#cmd dx_re_start_key_input                  $273
#cmd dx_process_act_key_input               $274
#cmd dx_draw_key_input_string               $275
#cmd dx_draw_key_input_extend_string        $276
#cmd dx_set_key_input_draw_area             $277
#cmd dx_set_key_input_select_area           $278
#cmd dx_set_key_input_draw_start_pos        $279
#cmd dx_get_key_input_draw_start_pos        $27a
#cmd dx_set_key_input_cursor_brink_time     $27b
#cmd dx_set_key_input_cursor_brink_flag     $27c
#cmd dx_set_key_input_string                $27d
#cmd dx_set_key_input_number                $27e
#cmd dx_set_key_input_number_to_float       $27f
#cmd dx_get_key_input_string                $280
#cmd dx_get_key_input_number                $281
#cmd dx_set_key_input_cursor_position       $282
#cmd dx_get_key_input_cursor_position       $283
#cmd dx_file_read_open                      $284
#cmd dx_file_read_close                     $285
#cmd dx_file_read_seek                      $286
#cmd dx_file_read_idle_chk                  $287
#cmd dx_file_read_eof                       $288
#cmd dx_file_read_gets                      $289
#cmd dx_file_read_fully_load                $28a
#cmd dx_file_read_fully_load_delete         $28b
#cmd dx_get_stream_function_default         $28c
#cmd dx_convert_full_path                   $28d
#cmd dx_check_hit_key_all                   $28e
#cmd dx_get_joypad_num                      $28f
#cmd dx_get_joypad_button_num               $290
#cmd dx_check_joypad_x_input                $291
#cmd dx_get_joypad_type                     $292
#cmd dx_set_joypad_input_to_key_input       $293
#cmd dx_set_joypad_dead_zone                $294
#cmd dx_set_joypad_default_dead_zone_all    $295
#cmd dx_start_joypad_vibration              $296
#cmd dx_stop_joypad_vibration               $297
#cmd dx_get_joypad_pov_state                $298
#cmd dx_re_setup_joypad                     $299
#cmd dx_re_setup_input_system               $29a
#cmd dx_set_use_joypad_vibration_flag       $29b
#cmd dx_make_graph                          $29c
#cmd dx_derivation_graph                    $29d
#cmd dx_derivation_graph_f                  $29e
#cmd dx_delete_sharing_graph                $29f
#cmd dx_get_graph_num                       $2a0
#cmd dx_fill_graph                          $2a1
#cmd dx_fill_rect_graph                     $2a2
#cmd dx_init_graph                          $2a3
#cmd dx_reload_file_graph_all               $2a4
#cmd dx_make_shadow_map                     $2a5
#cmd dx_delete_shadow_map                   $2a6
#cmd dx_set_shadow_map_light_direction      $2a7
#cmd dx_shadow_map_draw_setup               $2a8
#cmd dx_shadow_map_draw_end                 $2a9
#cmd dx_set_use_shadow_map                  $2aa
#cmd dx_set_shadow_map_draw_area            $2ab
#cmd dx_reset_shadow_map_draw_area          $2ac
#cmd dx_set_shadow_map_adjust_depth         $2ad
#cmd dx_test_draw_shadow_map                $2ae
#cmd dx_load_bmp_to_graph                   $2af
#cmd dx_load_reverse_graph                  $2b0
#cmd dx_load_blend_graph                    $2b1
#cmd dx_create_blend_graph_from_soft_image  $2b2
#cmd dx_create_graph_from_soft_image        $2b3
#cmd dx_create_graph_from_rect_soft_image   $2b4
#cmd dx_re_create_graph_from_soft_image     $2b5
#cmd dx_re_create_graph_from_rect_soft_image $2b6
#cmd dx_reload_graph                        $2b7
#cmd dx_reload_reverse_graph                $2b8
#cmd dx_set_graph_color_bit_depth           $2b9
#cmd dx_get_graph_color_bit_depth           $2ba
#cmd dx_set_create_graph_color_bit_depth    $2bb
#cmd dx_get_create_graph_color_bit_depth    $2bc
#cmd dx_set_create_graph_channel_bit_depth  $2bd
#cmd dx_get_create_graph_channel_bit_depth  $2be
#cmd dx_set_create_graph_init_graph_delete  $2bf
#cmd dx_get_create_graph_init_graph_delete  $2c0
#cmd dx_set_create_graph_handle             $2c1
#cmd dx_get_create_graph_handle             $2c2
#cmd dx_set_draw_valid_graph_create_flag    $2c3
#cmd dx_get_draw_valid_graph_create_flag    $2c4
#cmd dx_set_draw_valid_flag_of3_d_graph     $2c5
#cmd dx_set_left_up_color_is_trans_color_flag $2c6
#cmd dx_set_use_palette_graph_flag          $2c7
#cmd dx_set_use_blend_graph_create_flag     $2c8
#cmd dx_get_use_blend_graph_create_flag     $2c9
#cmd dx_set_use_alpha_test_graph_create_flag $2ca
#cmd dx_get_use_alpha_test_graph_create_flag $2cb
#cmd dx_set_use_alpha_test_flag             $2cc
#cmd dx_get_use_alpha_test_flag             $2cd
#cmd dx_set_cube_map_texture_create_flag    $2ce
#cmd dx_get_cube_map_texture_create_flag    $2cf
#cmd dx_set_use_no_blend_mode_param         $2d0
#cmd dx_set_draw_valid_alpha_channel_graph_create_flag $2d1
#cmd dx_get_draw_valid_alpha_channel_graph_create_flag $2d2
#cmd dx_set_draw_valid_float_type_graph_create_flag $2d3
#cmd dx_get_draw_valid_float_type_graph_create_flag $2d4
#cmd dx_set_draw_valid_graph_create_z_buffer_flag $2d5
#cmd dx_get_draw_valid_graph_create_z_buffer_flag $2d6
#cmd dx_set_create_draw_valid_graph_z_buffer_bit_depth $2d7
#cmd dx_get_create_draw_valid_graph_z_buffer_bit_depth $2d8
#cmd dx_set_create_draw_valid_graph_mip_levels $2d9
#cmd dx_get_create_draw_valid_graph_mip_levels $2da
#cmd dx_set_create_draw_valid_graph_channel_num $2db
#cmd dx_get_create_draw_valid_graph_channel_num $2dc
#cmd dx_set_create_draw_valid_graph_multi_sample $2dd
#cmd dx_set_draw_valid_multi_sample         $2de
#cmd dx_get_multi_sample_quality            $2df
#cmd dx_set_use_trans_color                 $2e0
#cmd dx_set_use_trans_color_graph_create_flag $2e1
#cmd dx_set_use_graph_alpha_channel         $2e2
#cmd dx_get_use_graph_alpha_channel         $2e3
#cmd dx_set_use_alpha_channel_graph_create_flag $2e4
#cmd dx_get_use_alpha_channel_graph_create_flag $2e5
#cmd dx_set_use_not_manage_texture_flag     $2e6
#cmd dx_get_use_not_manage_texture_flag     $2e7
#cmd dx_set_use_platform_texture_format     $2e8
#cmd dx_get_use_platform_texture_format     $2e9
#cmd dx_set_trans_color                     $2ea
#cmd dx_set_use_div_graph_flag              $2eb
#cmd dx_set_use_alpha_image_load_flag       $2ec
#cmd dx_set_use_max_texture_size            $2ed
#cmd dx_set_use_graph_base_data_backup      $2ee
#cmd dx_get_use_graph_base_data_backup      $2ef
#cmd dx_set_use_system_mem_graph_create_flag $2f0
#cmd dx_get_use_system_mem_graph_create_flag $2f1
#cmd dx_set_use_load_div_graph_size_check_flag $2f2
#cmd dx_get_use_load_div_graph_size_check_flag $2f3
#cmd dx_graph_un_lock                       $2f4
#cmd dx_set_use_graph_z_buffer              $2f5
#cmd dx_copy_graph_z_buffer_image           $2f6
#cmd dx_set_device_lost_delete_graph_flag   $2f7
#cmd dx_get_graph_mipmap_count              $2f8
#cmd dx_get_graph_file_path                 $2f9
#cmd dx_check_draw_valid_graph              $2fa
#cmd dx_get_valid_restore_shred_point       $2fb
#cmd dx_set_graph_palette                   $2fc
#cmd dx_reset_graph_palette                 $2fd
#cmd dx_draw_fill_box                       $2fe
#cmd dx_draw_line_box                       $2ff
#cmd dx_draw_oval                           $300
#cmd dx_draw_oval_aa                        $301
#cmd dx_draw_oval_rect                      $302
#cmd dx_draw_triangle_aa                    $303
#cmd dx_draw_quadrangle                     $304
#cmd dx_draw_quadrangle_aa                  $305
#cmd dx_draw_round_rect                     $306
#cmd dx_draw_round_rect_aa                  $307
#cmd dx_begin_aa_draw                       $308
#cmd dx_end_aa_draw                         $309
#cmd dx_draw_pixel3_d                       $30a
#cmd dx_draw_pixel3_dd                      $30b
#cmd dx_draw_line3_d                        $30c
#cmd dx_draw_line3_dd                       $30d
#cmd dx_draw_triangle3_d                    $30e
#cmd dx_draw_triangle3_dd                   $30f
#cmd dx_draw_cube3_dd                       $310
#cmd dx_draw_sphere3_dd                     $311
#cmd dx_draw_capsule3_d                     $312
#cmd dx_draw_capsule3_dd                    $313
#cmd dx_draw_cylinder3_d                    $314
#cmd dx_draw_cylinder3_dd                   $315
#cmd dx_draw_tube3_d                        $316
#cmd dx_draw_tube3_dd                       $317
#cmd dx_draw_cone3_d                        $318
#cmd dx_draw_cone3_dd                       $319
#cmd dx_load_graph_screen                   $31a
#cmd dx_draw_rota_graph2                    $31b
#cmd dx_draw_rota_graph3                    $31c
#cmd dx_draw_rota_graph_fast                $31d
#cmd dx_draw_rota_graph_fast2               $31e
#cmd dx_draw_rota_graph_fast3               $31f
#cmd dx_draw_turn_graph                     $320
#cmd dx_draw_reverse_graph                  $321
#cmd dx_draw_graph_f                        $322
#cmd dx_draw_extend_graph_f                 $323
#cmd dx_draw_rota_graph_f                   $324
#cmd dx_draw_rota_graph2_f                  $325
#cmd dx_draw_rota_graph3_f                  $326
#cmd dx_draw_rota_graph_fast_f              $327
#cmd dx_draw_rota_graph_fast2_f             $328
#cmd dx_draw_rota_graph_fast3_f             $329
#cmd dx_draw_modi_graph_f                   $32a
#cmd dx_draw_turn_graph_f                   $32b
#cmd dx_draw_reverse_graph_f                $32c
#cmd dx_draw_tile                           $32d
#cmd dx_draw_rect_extend_graph              $32e
#cmd dx_draw_rect_rota_graph2               $32f
#cmd dx_draw_rect_rota_graph3               $330
#cmd dx_draw_rect_rota_graph_fast           $331
#cmd dx_draw_rect_rota_graph_fast2          $332
#cmd dx_draw_rect_rota_graph_fast3          $333
#cmd dx_draw_rect_modi_graph                $334
#cmd dx_draw_rect_graph_f                   $335
#cmd dx_draw_rect_graph_f2                  $336
#cmd dx_draw_rect_extend_graph_f            $337
#cmd dx_draw_rect_extend_graph_f2           $338
#cmd dx_draw_rect_rota_graph_f              $339
#cmd dx_draw_rect_rota_graph2_f             $33a
#cmd dx_draw_rect_rota_graph3_f             $33b
#cmd dx_draw_rect_rota_graph_fast_f         $33c
#cmd dx_draw_rect_rota_graph_fast2_f        $33d
#cmd dx_draw_rect_rota_graph_fast3_f        $33e
#cmd dx_draw_rect_modi_graph_f              $33f
#cmd dx_draw_blend_graph                    $340
#cmd dx_draw_blend_graph_f                  $341
#cmd dx_draw_blend_graph_pos                $342
#cmd dx_draw_circle_gauge                   $343
#cmd dx_draw_circle_gauge_f                 $344
#cmd dx_draw_polygon3_d_use_vertex_buffer   $345
#cmd dx_draw_polygon_indexed3_d_use_vertex_buffer $346
#cmd dx_draw_graph3_d                       $347
#cmd dx_draw_extend_graph3_d                $348
#cmd dx_draw_rota_graph3_d                  $349
#cmd dx_draw_rota2_graph3_d                 $34a
#cmd dx_draw_modi_billboard3_d              $34b
#cmd dx_draw_billboard3_d                   $34c
#cmd dx_get_draw_mode                       $34d
#cmd dx_set_draw_alpha_test                 $34e
#cmd dx_set_blend_graph                     $34f
#cmd dx_set_blend_graph_position            $350
#cmd dx_set_draw_add_color                  $351
#cmd dx_set_write_alpha_channel_flag        $352
#cmd dx_get_write_alpha_channel_flag        $353
#cmd dx_check_separate_alpha_blend_enable   $354
#cmd dx_set_ignore_draw_graph_color         $355
#cmd dx_get_ignore_draw_graph_color         $356
#cmd dx_set_max_anisotropy                  $357
#cmd dx_get_max_anisotropy                  $358
#cmd dx_set_use_large3_d_position_support   $359
#cmd dx_set_use_z_buffer_flag               $35a
#cmd dx_set_write_z_buffer_flag             $35b
#cmd dx_set_z_bias                          $35c
#cmd dx_set_z_bias3_d                       $35d
#cmd dx_set_draw_z                          $35e
#cmd dx_set_use_reversed_z                  $35f
#cmd dx_set_draw_area                       $360
#cmd dx_set_draw_area_full                  $361
#cmd dx_set_draw3_d_scale                   $362
#cmd dx_run_restore_shred                   $363
#cmd dx_reset_transform_to2_d               $364
#cmd dx_set_def_transform_matrix            $365
#cmd dx_set_use_culling_flag                $366
#cmd dx_get_use_back_culling                $367
#cmd dx_set_use_right_hand_clipping_process $368
#cmd dx_get_use_right_hand_clipping_process $369
#cmd dx_set_texture_address_mode_uv         $36a
#cmd dx_set_texture_address_transform       $36b
#cmd dx_set_texture_address_transform_matrix $36c
#cmd dx_reset_texture_address_transform     $36d
#cmd dx_set_fog_enable                      $36e
#cmd dx_get_fog_enable                      $36f
#cmd dx_get_fog_mode                        $370
#cmd dx_set_fog_color                       $371
#cmd dx_set_fog_start_end                   $372
#cmd dx_set_fog_density                     $373
#cmd dx_set_vertical_fog_enable             $374
#cmd dx_get_vertical_fog_enable             $375
#cmd dx_get_vertical_fog_mode               $376
#cmd dx_set_vertical_fog_color              $377
#cmd dx_set_vertical_fog_start_end          $378
#cmd dx_set_vertical_fog_density            $379
#cmd dx_get_draw_screen_graph               $37a
#cmd dx_blt_draw_valid_graph                $37b
#cmd dx_screen_copy                         $37c
#cmd dx_wait_v_sync                         $37d
#cmd dx_cls_draw_screen                     $37e
#cmd dx_get_draw_screen                     $37f
#cmd dx_get_active_graph                    $380
#cmd dx_set_use_set_draw_screen_setting_reset $381
#cmd dx_get_use_set_draw_screen_setting_reset $382
#cmd dx_set_draw_z_buffer                   $383
#cmd dx_get_use_full_screen_resolution_mode $384
#cmd dx_set_emulation320x240                $385
#cmd dx_set_z_buffer_size                   $386
#cmd dx_set_z_buffer_bit_depth              $387
#cmd dx_get_wait_v_sync_flag                $388
#cmd dx_set_full_scene_anti_aliasing_mode   $389
#cmd dx_set_graph_display_area              $38a
#cmd dx_set_change_screen_mode_graphics_system_reset_flag $38b
#cmd dx_get_screen_bit_depth                $38c
#cmd dx_get_color_bit_depth                 $38d
#cmd dx_get_change_display_flag             $38e
#cmd dx_get_refresh_rate                    $38f
#cmd dx_get_display_num                     $390
#cmd dx_get_display_mode_num                $391
#cmd dx_get_multi_draw_screen_num           $392
#cmd dx_get_draw_float_coord_type           $393
#cmd dx_set_use_normal_draw_shader          $394
#cmd dx_set_use_software_render_mode_flag   $395
#cmd dx_set_not_use3_d_flag                 $396
#cmd dx_set_use3_d_flag                     $397
#cmd dx_get_use3_d_flag                     $398
#cmd dx_set_screen_mem_to_vram_flag         $399
#cmd dx_get_screen_mem_to_system_mem_flag   $39a
#cmd dx_restore_graph_system                $39b
#cmd dx_set_use_hardware_vertex_processing  $39c
#cmd dx_set_use_pixel_lighting              $39d
#cmd dx_set_use_old_draw_modi_graph_code_flag $39e
#cmd dx_set_use_vram_flag                   $39f
#cmd dx_get_use_vram_flag                   $3a0
#cmd dx_set_basic_blend_flag                $3a1
#cmd dx_set_use_basic_graph_draw3_d_device_method_flag $3a2
#cmd dx_set_use_display_index               $3a3
#cmd dx_render_vertex                       $3a4
#cmd dx_get_draw_call_count                 $3a5
#cmd dx_save_draw_screen_to_bmp             $3a6
#cmd dx_save_draw_screen_to_dds             $3a7
#cmd dx_save_draw_screen_to_jpeg            $3a8
#cmd dx_save_draw_screen_to_png             $3a9
#cmd dx_save_draw_valid_graph               $3aa
#cmd dx_save_draw_valid_graph_to_bmp        $3ab
#cmd dx_save_draw_valid_graph_to_dds        $3ac
#cmd dx_save_draw_valid_graph_to_jpeg       $3ad
#cmd dx_save_draw_valid_graph_to_png        $3ae
#cmd dx_delete_vertex_buffer                $3af
#cmd dx_init_vertex_buffer                  $3b0
#cmd dx_update_vertex_buffer                $3b1
#cmd dx_delete_index_buffer                 $3b2
#cmd dx_init_index_buffer                   $3b3
#cmd dx_update_index_buffer                 $3b4
#cmd dx_get_max_primitive_count             $3b5
#cmd dx_get_max_vertex_index                $3b6
#cmd dx_get_valid_shader_version            $3b7
#cmd dx_load_vertex_shader                  $3b8
#cmd dx_load_geometry_shader                $3b9
#cmd dx_load_pixel_shader                   $3ba
#cmd dx_delete_shader                       $3bb
#cmd dx_init_shader                         $3bc
#cmd dx_get_const_index_to_shader           $3bd
#cmd dx_get_const_count_to_shader           $3be
#cmd dx_set_vs_const_sf                     $3bf
#cmd dx_set_vs_const_f                      $3c0
#cmd dx_set_vs_const_f_mtx                  $3c1
#cmd dx_set_vs_const_f_mtx_t                $3c2
#cmd dx_set_vs_const_si                     $3c3
#cmd dx_reset_vs_const_f                    $3c4
#cmd dx_reset_vs_const_i                    $3c5
#cmd dx_reset_vs_const_b                    $3c6
#cmd dx_set_ps_const_sf                     $3c7
#cmd dx_set_ps_const_f                      $3c8
#cmd dx_set_ps_const_f_mtx                  $3c9
#cmd dx_set_ps_const_f_mtx_t                $3ca
#cmd dx_set_ps_const_si                     $3cb
#cmd dx_reset_ps_const_f                    $3cc
#cmd dx_reset_ps_const_i                    $3cd
#cmd dx_reset_ps_const_b                    $3ce
#cmd dx_set_render_target_to_shader         $3cf
#cmd dx_set_use_texture_to_shader           $3d0
#cmd dx_set_use_vertex_shader               $3d1
#cmd dx_set_use_geometry_shader             $3d2
#cmd dx_set_use_pixel_shader                $3d3
#cmd dx_draw_billboard3_d_to_shader         $3d4
#cmd dx_draw_polygon3_d_to_shader_use_vertex_buffer $3d5
#cmd dx_draw_polygon_indexed3_d_to_shader_use_vertex_buffer $3d6
#cmd dx_init_shader_constant_buffer         $3d7
#cmd dx_create_shader_constant_buffer       $3d8
#cmd dx_delete_shader_constant_buffer       $3d9
#cmd dx_update_shader_constant_buffer       $3da
#cmd dx_set_graph_blend_scaling_filter_mode $3db
#cmd dx_play_movie                          $3dc
#cmd dx_open_movie_to_graph                 $3dd
#cmd dx_add_movie_frame_to_graph            $3de
#cmd dx_seek_movie_to_graph                 $3df
#cmd dx_set_play_speed_rate_movie_to_graph  $3e0
#cmd dx_get_movie_state_to_graph            $3e1
#cmd dx_set_movie_volume_to_graph           $3e2
#cmd dx_get_movie_volume_to_graph           $3e3
#cmd dx_change_movie_volume_to_graph        $3e4
#cmd dx_get_movie_volume_to_graph2          $3e5
#cmd dx_get_movie_total_frame_to_graph      $3e6
#cmd dx_tell_movie_to_graph                 $3e7
#cmd dx_tell_movie_to_graph_to_frame        $3e8
#cmd dx_seek_movie_to_graph_to_frame        $3e9
#cmd dx_get_last_update_time_movie_to_graph $3ea
#cmd dx_update_movie_to_graph               $3eb
#cmd dx_set_movie_right_image_alpha_flag    $3ec
#cmd dx_set_movie_color_a8_r8_g8_b8_flag    $3ed
#cmd dx_set_movie_use_yuv_format_surface_flag $3ee
#cmd dx_set_camera_near_far                 $3ef
#cmd dx_set_camera_near_far_d               $3f0
#cmd dx_set_camera_position_and_target_up_vec_yd $3f1
#cmd dx_set_camera_position_and_target_and_up_vec $3f2
#cmd dx_set_camera_position_and_target_and_up_vec_d $3f3
#cmd dx_set_camera_position_and_angle       $3f4
#cmd dx_set_camera_position_and_angle_d     $3f5
#cmd dx_set_camera_view_matrix              $3f6
#cmd dx_set_camera_view_matrix_d            $3f7
#cmd dx_set_camera_screen_center            $3f8
#cmd dx_set_camera_screen_center_d          $3f9
#cmd dx_setup_camera_perspective_d          $3fa
#cmd dx_setup_camera_ortho                  $3fb
#cmd dx_setup_camera_ortho_d                $3fc
#cmd dx_setup_camera_projection_matrix      $3fd
#cmd dx_setup_camera_projection_matrix_d    $3fe
#cmd dx_set_camera_dot_aspect               $3ff
#cmd dx_set_camera_dot_aspect_d             $400
#cmd dx_check_camera_view_clip              $401
#cmd dx_check_camera_view_clip_d            $402
#cmd dx_check_camera_view_clip_dir          $403
#cmd dx_check_camera_view_clip_dir_d        $404
#cmd dx_check_camera_view_clip_box          $405
#cmd dx_check_camera_view_clip_box_d        $406
#cmd dx_set_material_use_vert_dif_color     $407
#cmd dx_set_material_use_vert_spc_color     $408
#cmd dx_set_use_specular                    $409
#cmd dx_set_global_ambient_light            $40a
#cmd dx_set_use_light_angle_attenuation     $40b
#cmd dx_set_use_half_lambert_lighting       $40c
#cmd dx_change_light_type_dir               $40d
#cmd dx_change_light_type_spot              $40e
#cmd dx_change_light_type_point             $40f
#cmd dx_get_light_type                      $410
#cmd dx_set_light_enable                    $411
#cmd dx_get_light_enable                    $412
#cmd dx_set_light_dif_color                 $413
#cmd dx_set_light_spc_color                 $414
#cmd dx_set_light_amb_color                 $415
#cmd dx_set_light_position                  $416
#cmd dx_set_light_range_atten               $417
#cmd dx_set_light_angle                     $418
#cmd dx_set_light_use_shadow_map            $419
#cmd dx_create_dir_light_handle             $41a
#cmd dx_create_spot_light_handle            $41b
#cmd dx_create_point_light_handle           $41c
#cmd dx_delete_light_handle                 $41d
#cmd dx_delete_light_handle_all             $41e
#cmd dx_set_light_type_handle               $41f
#cmd dx_set_light_enable_handle             $420
#cmd dx_set_light_dif_color_handle          $421
#cmd dx_set_light_spc_color_handle          $422
#cmd dx_set_light_amb_color_handle          $423
#cmd dx_set_light_direction_handle          $424
#cmd dx_set_light_position_handle           $425
#cmd dx_set_light_range_atten_handle        $426
#cmd dx_set_light_angle_handle              $427
#cmd dx_set_light_use_shadow_map_handle     $428
#cmd dx_get_light_type_handle               $429
#cmd dx_get_light_enable_handle             $42a
#cmd dx_get_enable_light_handle_num         $42b
#cmd dx_get_enable_light_handle             $42c
#cmd dx_create_mask_screen                  $42d
#cmd dx_delete_mask_screen                  $42e
#cmd dx_set_use_mask_screen_flag            $42f
#cmd dx_get_use_mask_screen_flag            $430
#cmd dx_fill_mask_screen                    $431
#cmd dx_set_mask_screen_graph               $432
#cmd dx_init_mask                           $433
#cmd dx_make_mask                           $434
#cmd dx_delete_mask                         $435
#cmd dx_load_mask                           $436
#cmd dx_draw_mask                           $437
#cmd dx_draw_string_mask                    $438
#cmd dx_draw_string_mask_to_handle          $439
#cmd dx_draw_fill_mask                      $43a
#cmd dx_set_mask_reverse_effect_flag        $43b
#cmd dx_get_mask_screen_data                $43c
#cmd dx_get_mask_use_flag                   $43d
#cmd dx_enum_font_name                      $43e
#cmd dx_init_font_to_handle                 $43f
#cmd dx_load_font_data_to_handle            $440
#cmd dx_set_font_space_to_handle            $441
#cmd dx_set_font_line_space_to_handle       $442
#cmd dx_delete_font_to_handle               $443
#cmd dx_add_font_image_to_handle            $444
#cmd dx_sub_font_image_to_handle            $445
#cmd dx_add_substitution_font_to_handle     $446
#cmd dx_sub_substitution_font_to_handle     $447
#cmd dx_change_font_from_handle             $448
#cmd dx_change_font_type                    $449
#cmd dx_get_font_size                       $44a
#cmd dx_get_font_edge_size                  $44b
#cmd dx_set_font_space                      $44c
#cmd dx_get_font_space                      $44d
#cmd dx_set_font_line_space                 $44e
#cmd dx_get_font_line_space                 $44f
#cmd dx_set_default_font_state              $450
#cmd dx_get_default_font_handle             $451
#cmd dx_get_font_max_cache_char_num         $452
#cmd dx_get_font_max_width                  $453
#cmd dx_get_font_ascent                     $454
#cmd dx_get_draw_string_width               $455
#cmd dx_get_draw_extend_string_width        $456
#cmd dx_get_font_max_cache_char_num_to_handle $457
#cmd dx_get_font_max_width_to_handle        $458
#cmd dx_get_font_ascent_to_handle           $459
#cmd dx_get_font_size_to_handle             $45a
#cmd dx_get_font_edge_size_to_handle        $45b
#cmd dx_get_font_space_to_handle            $45c
#cmd dx_get_font_line_space_to_handle       $45d
#cmd dx_get_draw_string_width_to_handle     $45e
#cmd dx_get_draw_extend_string_width_to_handle $45f
#cmd dx_check_font_cache_to_texture_flag    $460
#cmd dx_check_font_chache_to_texture_flag   $461
#cmd dx_check_font_handle_valid             $462
#cmd dx_clear_font_cache_to_handle          $463
#cmd dx_set_font_cache_to_texture_flag      $464
#cmd dx_get_font_cache_to_texture_flag      $465
#cmd dx_set_font_chache_to_texture_flag     $466
#cmd dx_get_font_chache_to_texture_flag     $467
#cmd dx_set_font_cache_texture_color_bit_depth $468
#cmd dx_get_font_cache_texture_color_bit_depth $469
#cmd dx_set_font_cache_char_num             $46a
#cmd dx_get_font_cache_char_num             $46b
#cmd dx_set_font_cache_use_premul_alpha_flag $46c
#cmd dx_get_font_cache_use_premul_alpha_flag $46d
#cmd dx_set_font_use_adjust_size_flag       $46e
#cmd dx_get_font_use_adjust_size_flag       $46f
#cmd dx_set_font_only_draw_type             $470
#cmd dx_get_font_only_draw_type             $471
#cmd dx_set_font_ignore_lf_flag             $472
#cmd dx_get_font_ignore_lf_flag             $473
#cmd dx_draw_v_string                       $474
#cmd dx_draw_extend_string                  $475
#cmd dx_draw_extend_v_string                $476
#cmd dx_draw_rota_string                    $477
#cmd dx_draw_modi_string                    $478
#cmd dx_draw_string_f                       $479
#cmd dx_draw_v_string_f                     $47a
#cmd dx_draw_extend_string_f                $47b
#cmd dx_draw_extend_v_string_f              $47c
#cmd dx_draw_rota_string_f                  $47d
#cmd dx_draw_modi_string_f                  $47e
#cmd dx_draw_number_to_i                    $47f
#cmd dx_draw_number_to_f                    $480
#cmd dx_draw_number_plus_to_i               $481
#cmd dx_draw_number_plus_to_f               $482
#cmd dx_draw_string_to_handle               $483
#cmd dx_draw_v_string_to_handle             $484
#cmd dx_draw_extend_string_to_handle        $485
#cmd dx_draw_extend_v_string_to_handle      $486
#cmd dx_draw_rota_string_to_handle          $487
#cmd dx_draw_modi_string_to_handle          $488
#cmd dx_draw_string_f_to_handle             $489
#cmd dx_draw_v_string_f_to_handle           $48a
#cmd dx_draw_extend_string_f_to_handle      $48b
#cmd dx_draw_extend_v_string_f_to_handle    $48c
#cmd dx_draw_rota_string_f_to_handle        $48d
#cmd dx_draw_modi_string_f_to_handle        $48e
#cmd dx_draw_number_to_i_to_handle          $48f
#cmd dx_draw_number_to_f_to_handle          $490
#cmd dx_draw_number_plus_to_i_to_handle     $491
#cmd dx_draw_number_plus_to_f_to_handle     $492
#cmd dx_hit_check_triangle_triangle         $493
#cmd dx_hit_check_triangle_triangle_d       $494
#cmd dx_hit_check_triangle_triangle_2_d     $495
#cmd dx_hit_check_triangle_triangle_d_2_d   $496
#cmd dx_hit_check_point_cone                $497
#cmd dx_hit_check_point_cone_d              $498
#cmd dx_hit_check_line_sphere               $499
#cmd dx_hit_check_line_sphere_d             $49a
#cmd dx_hit_check_sphere_sphere             $49b
#cmd dx_hit_check_sphere_sphere_d           $49c
#cmd dx_hit_check_sphere_capsule            $49d
#cmd dx_hit_check_sphere_capsule_d          $49e
#cmd dx_hit_check_sphere_triangle           $49f
#cmd dx_hit_check_sphere_triangle_d         $4a0
#cmd dx_hit_check_capsule_capsule           $4a1
#cmd dx_hit_check_capsule_capsule_d         $4a2
#cmd dx_hit_check_capsule_triangle          $4a3
#cmd dx_hit_check_capsule_triangle_d        $4a4
#cmd dx_set_use_fast_load_flag              $4a5
#cmd dx_get_graph_data_shaved_mode          $4a6
#cmd dx_set_use_premul_alpha_convert_load   $4a7
#cmd dx_get_use_premul_alpha_convert_load   $4a8
#cmd dx_set_use_convert_normal_format_load  $4a9
#cmd dx_get_use_convert_normal_format_load  $4aa
#cmd dx_init_soft_image                     $4ab
#cmd dx_load_soft_image                     $4ac
#cmd dx_load_argb8_color_soft_image         $4ad
#cmd dx_load_xrgb8_color_soft_image         $4ae
#cmd dx_make_soft_image                     $4af
#cmd dx_make_argbf32_color_soft_image       $4b0
#cmd dx_make_argbf16_color_soft_image       $4b1
#cmd dx_make_xrgb8_color_soft_image         $4b2
#cmd dx_make_argb8_color_soft_image         $4b3
#cmd dx_make_rgba8_color_soft_image         $4b4
#cmd dx_make_abgr8_color_soft_image         $4b5
#cmd dx_make_bgra8_color_soft_image         $4b6
#cmd dx_make_argb4_color_soft_image         $4b7
#cmd dx_make_a1_r5_g5_b5_color_soft_image   $4b8
#cmd dx_make_x1_r5_g5_b5_color_soft_image   $4b9
#cmd dx_make_r5_g5_b5_a1_color_soft_image   $4ba
#cmd dx_make_r5_g6_b5_color_soft_image      $4bb
#cmd dx_make_rgb8_color_soft_image          $4bc
#cmd dx_make_pal8_color_soft_image          $4bd
#cmd dx_delete_soft_image                   $4be
#cmd dx_check_palette_soft_image            $4bf
#cmd dx_check_alpha_soft_image              $4c0
#cmd dx_check_pixel_alpha_soft_image        $4c1
#cmd dx_get_draw_screen_soft_image          $4c2
#cmd dx_get_draw_screen_soft_image_dest_pos $4c3
#cmd dx_fill_soft_image                     $4c4
#cmd dx_clear_rect_soft_image               $4c5
#cmd dx_set_palette_soft_image              $4c6
#cmd dx_draw_pixel_pal_code_soft_image      $4c7
#cmd dx_get_pixel_pal_code_soft_image       $4c8
#cmd dx_get_pitch_soft_image                $4c9
#cmd dx_draw_pixel_soft_image               $4ca
#cmd dx_draw_pixel_soft_image_f             $4cb
#cmd dx_draw_line_soft_image                $4cc
#cmd dx_draw_circle_soft_image              $4cd
#cmd dx_blt_soft_image                      $4ce
#cmd dx_blt_soft_image_with_trans_color     $4cf
#cmd dx_blt_soft_image_with_alpha_blend     $4d0
#cmd dx_reverse_soft_image_h                $4d1
#cmd dx_reverse_soft_image_v                $4d2
#cmd dx_reverse_soft_image                  $4d3
#cmd dx_convert_premul_alpha_soft_image     $4d4
#cmd dx_convert_interp_alpha_soft_image     $4d5
#cmd dx_blt_string_soft_image               $4d6
#cmd dx_draw_soft_image                     $4d7
#cmd dx_save_soft_image_to_bmp              $4d8
#cmd dx_save_soft_image_to_dds              $4d9
#cmd dx_save_soft_image_to_png              $4da
#cmd dx_save_soft_image_to_jpeg             $4db
#cmd dx_init_sound_mem                      $4dc
#cmd dx_add_sound_data                      $4dd
#cmd dx_add_stream_sound_mem_to_file        $4de
#cmd dx_setup_stream_sound_mem              $4df
#cmd dx_play_stream_sound_mem               $4e0
#cmd dx_check_stream_sound_mem              $4e1
#cmd dx_stop_stream_sound_mem               $4e2
#cmd dx_set_stream_sound_current_position   $4e3
#cmd dx_set_stream_sound_current_time       $4e4
#cmd dx_process_stream_sound_mem            $4e5
#cmd dx_process_stream_sound_mem_all        $4e6
#cmd dx_load_sound_mem2                     $4e7
#cmd dx_load_bgm                            $4e8
#cmd dx_load_sound_mem_base                 $4e9
#cmd dx_load_sound_mem_to_buf_num_sitei     $4ea
#cmd dx_duplicate_sound_mem                 $4eb
#cmd dx_load_sound_mem_from_soft_sound      $4ec
#cmd dx_change_pan_sound_mem                $4ed
#cmd dx_get_pan_sound_mem                   $4ee
#cmd dx_change_volume_sound_mem             $4ef
#cmd dx_get_volume_sound_mem                $4f0
#cmd dx_get_volume_sound_mem2               $4f1
#cmd dx_set_channel_volume_sound_mem        $4f2
#cmd dx_change_channel_volume_sound_mem     $4f3
#cmd dx_get_channel_volume_sound_mem        $4f4
#cmd dx_get_channel_volume_sound_mem2       $4f5
#cmd dx_set_frequency_sound_mem             $4f6
#cmd dx_get_frequency_sound_mem             $4f7
#cmd dx_reset_frequency_sound_mem           $4f8
#cmd dx_set_next_play_pan_sound_mem         $4f9
#cmd dx_change_next_play_pan_sound_mem      $4fa
#cmd dx_set_next_play_volume_sound_mem      $4fb
#cmd dx_change_next_play_volume_sound_mem   $4fc
#cmd dx_set_next_play_channel_volume_sound_mem $4fd
#cmd dx_change_next_play_channel_volume_sound_mem $4fe
#cmd dx_set_next_play_frequency_sound_mem   $4ff
#cmd dx_set_current_position_sound_mem      $500
#cmd dx_set_sound_current_position          $501
#cmd dx_set_sound_current_time              $502
#cmd dx_set_loop_pos_sound_mem              $503
#cmd dx_set_loop_time_pos_sound_mem         $504
#cmd dx_set_loop_sample_pos_sound_mem       $505
#cmd dx_set_loop_start_time_pos_sound_mem   $506
#cmd dx_set_loop_start_sample_pos_sound_mem $507
#cmd dx_set_loop_area_time_pos_sound_mem    $508
#cmd dx_set_loop_area_sample_pos_sound_mem  $509
#cmd dx_set_play_finish_delete_sound_mem    $50a
#cmd dx_set3_d_position_sound_mem           $50b
#cmd dx_set3_d_radius_sound_mem             $50c
#cmd dx_set3_d_velocity_sound_mem           $50d
#cmd dx_set_next_play3_d_position_sound_mem $50e
#cmd dx_set_next_play3_d_radius_sound_mem   $50f
#cmd dx_set_next_play3_d_velocity_sound_mem $510
#cmd dx_get_ogg_comment_num                 $511
#cmd dx_set_create_sound_data_type          $512
#cmd dx_get_create_sound_data_type          $513
#cmd dx_set_create_sound_pitch_rate         $514
#cmd dx_set_create_sound_time_stretch_rate  $515
#cmd dx_set_create_sound_loop_area_time_pos $516
#cmd dx_set_create_sound_loop_area_sample_pos $517
#cmd dx_set_create_sound_ignore_loop_area_info $518
#cmd dx_get_create_sound_ignore_loop_area_info $519
#cmd dx_set_disable_read_sound_function_mask $51a
#cmd dx_get_disable_read_sound_function_mask $51b
#cmd dx_set_enable_sound_capture_flag       $51c
#cmd dx_set_use_old_volume_calc_flag        $51d
#cmd dx_get_sound_current_time_type         $51e
#cmd dx_set_create3_d_sound_flag            $51f
#cmd dx_set3_d_sound_one_metre              $520
#cmd dx_set3_d_sound_listener_pos_and_front_pos_up_vec_y $521
#cmd dx_set3_d_sound_listener_pos_and_front_pos_and_up_vec $522
#cmd dx_set3_d_sound_listener_velocity      $523
#cmd dx_set3_d_sound_listener_cone_angle    $524
#cmd dx_set3_d_sound_listener_cone_volume   $525
#cmd dx_set_beep_frequency                  $526
#cmd dx_play_beep                           $527
#cmd dx_stop_beep                           $528
#cmd dx_play_sound_file                     $529
#cmd dx_play_sound                          $52a
#cmd dx_play_sound_dx                       $52b
#cmd dx_check_sound_file                    $52c
#cmd dx_check_sound                         $52d
#cmd dx_stop_sound_file                     $52e
#cmd dx_stop_sound                          $52f
#cmd dx_set_volume_sound_file               $530
#cmd dx_set_volume_sound                    $531
#cmd dx_init_soft_sound                     $532
#cmd dx_load_soft_sound                     $533
#cmd dx_make_soft_sound                     $534
#cmd dx_make_soft_sound2_ch16_bit44_k_hz    $535
#cmd dx_make_soft_sound2_ch16_bit22_k_hz    $536
#cmd dx_make_soft_sound2_ch8_bit44_k_hz     $537
#cmd dx_make_soft_sound2_ch8_bit22_k_hz     $538
#cmd dx_make_soft_sound1_ch16_bit44_k_hz    $539
#cmd dx_make_soft_sound1_ch16_bit22_k_hz    $53a
#cmd dx_make_soft_sound1_ch8_bit44_k_hz     $53b
#cmd dx_make_soft_sound1_ch8_bit22_k_hz     $53c
#cmd dx_make_soft_sound_custom              $53d
#cmd dx_delete_soft_sound                   $53e
#cmd dx_save_soft_sound                     $53f
#cmd dx_write_soft_sound_data               $540
#cmd dx_write_soft_sound_data_f             $541
#cmd dx_write_time_stretch_soft_sound_data  $542
#cmd dx_write_pitch_shift_soft_sound_data   $543
#cmd dx_init_soft_sound_player              $544
#cmd dx_make_soft_sound_player              $545
#cmd dx_make_soft_sound_player2_ch16_bit44_k_hz $546
#cmd dx_make_soft_sound_player2_ch16_bit22_k_hz $547
#cmd dx_make_soft_sound_player2_ch8_bit44_k_hz $548
#cmd dx_make_soft_sound_player2_ch8_bit22_k_hz $549
#cmd dx_make_soft_sound_player1_ch16_bit44_k_hz $54a
#cmd dx_make_soft_sound_player1_ch16_bit22_k_hz $54b
#cmd dx_make_soft_sound_player1_ch8_bit44_k_hz $54c
#cmd dx_make_soft_sound_player1_ch8_bit22_k_hz $54d
#cmd dx_make_soft_sound_player_custom       $54e
#cmd dx_delete_soft_sound_player            $54f
#cmd dx_add_data_soft_sound_player          $550
#cmd dx_add_one_data_soft_sound_player      $551
#cmd dx_start_soft_sound_player             $552
#cmd dx_check_start_soft_sound_player       $553
#cmd dx_stop_soft_sound_player              $554
#cmd dx_reset_soft_sound_player             $555
#cmd dx_check_soft_sound_player_none_data   $556
#cmd dx_delete_music_mem                    $557
#cmd dx_load_music_mem                      $558
#cmd dx_play_music_mem                      $559
#cmd dx_stop_music_mem                      $55a
#cmd dx_check_music_mem                     $55b
#cmd dx_set_volume_music_mem                $55c
#cmd dx_get_music_mem_position              $55d
#cmd dx_init_music_mem                      $55e
#cmd dx_process_music_mem                   $55f
#cmd dx_play_music                          $560
#cmd dx_set_volume_music                    $561
#cmd dx_stop_music                          $562
#cmd dx_check_music                         $563
#cmd dx_get_music_position                  $564
#cmd dx_select_midi_mode                    $565
#cmd dx_set_use_dx_archive_flag             $566
#cmd dx_set_dx_archive_priority             $567
#cmd dx_set_dx_archive_extension            $568
#cmd dx_set_dx_archive_key_string           $569
#cmd dx_dx_archive_pre_load                 $56a
#cmd dx_dx_archive_check_idle               $56b
#cmd dx_dx_archive_release                  $56c
#cmd dx_dx_archive_check_file               $56d
#cmd dx_mv1_duplicate_model                 $56e
#cmd dx_mv1_create_clone_model              $56f
#cmd dx_mv1_init_model                      $570
#cmd dx_mv1_set_load_model_re_make_normal   $571
#cmd dx_mv1_set_load_model_re_make_normal_smoothing_angle $572
#cmd dx_mv1_set_load_model_ignore_scaling   $573
#cmd dx_mv1_set_load_model_position_optimize $574
#cmd dx_mv1_set_load_model_not_eq_normal_side_add_zero_area_polygon $575
#cmd dx_mv1_set_load_model_physics_world_gravity $576
#cmd dx_mv1_set_load_calc_physics_world_gravity $577
#cmd dx_mv1_set_load_model_physics_calc_precision $578
#cmd dx_mv1_add_load_model_disable_physics_name_word $579
#cmd dx_mv1_reset_load_model_disable_physics_name_word $57a
#cmd dx_mv1_set_load_model_anim_file_path   $57b
#cmd dx_mv1_set_load_model_use_pack_draw    $57c
#cmd dx_mv1_set_load_model_triangle_list_use_max_bone_num $57d
#cmd dx_mv1_set_load_model_texture_load     $57e
#cmd dx_mv1_set_load_model_ignore_ik        $57f
#cmd dx_mv1_save_model_to_mv1_file          $580
#cmd dx_mv1_save_model_to_x_file            $581
#cmd dx_mv1_draw_frame                      $582
#cmd dx_mv1_draw_mesh                       $583
#cmd dx_mv1_draw_triangle_list              $584
#cmd dx_mv1_draw_model_debug                $585
#cmd dx_mv1_set_use_orig_shader             $586
#cmd dx_mv1_set_position_d                  $587
#cmd dx_mv1_set_rotation_zy_axis            $588
#cmd dx_mv1_set_rotation_y_use_dir          $589
#cmd dx_mv1_set_rotation_matrix             $58a
#cmd dx_mv1_set_matrix                      $58b
#cmd dx_mv1_set_matrix_d                    $58c
#cmd dx_mv1_set_visible                     $58d
#cmd dx_mv1_get_visible                     $58e
#cmd dx_mv1_set_mesh_category_visible       $58f
#cmd dx_mv1_get_mesh_category_visible       $590
#cmd dx_mv1_set_dif_color_scale             $591
#cmd dx_mv1_set_spc_color_scale             $592
#cmd dx_mv1_set_emi_color_scale             $593
#cmd dx_mv1_set_amb_color_scale             $594
#cmd dx_mv1_get_semi_trans_state            $595
#cmd dx_mv1_set_opacity_rate                $596
#cmd dx_mv1_set_use_draw_mul_alpha_color    $597
#cmd dx_mv1_get_use_draw_mul_alpha_color    $598
#cmd dx_mv1_set_use_z_buffer                $599
#cmd dx_mv1_set_write_z_buffer              $59a
#cmd dx_mv1_set_z_bias                      $59b
#cmd dx_mv1_set_use_vert_dif_color          $59c
#cmd dx_mv1_set_use_vert_spc_color          $59d
#cmd dx_mv1_set_sample_filter_mode          $59e
#cmd dx_mv1_set_max_anisotropy              $59f
#cmd dx_mv1_set_wire_frame_draw_flag        $5a0
#cmd dx_mv1_refresh_vert_color_from_material $5a1
#cmd dx_mv1_set_physics_world_gravity       $5a2
#cmd dx_mv1_physics_calculation             $5a3
#cmd dx_mv1_physics_reset_state             $5a4
#cmd dx_mv1_set_prioritize_physics_over_anim_flag $5a5
#cmd dx_mv1_set_use_shape_flag              $5a6
#cmd dx_mv1_get_material_number_order_flag  $5a7
#cmd dx_mv1_attach_anim                     $5a8
#cmd dx_mv1_detach_anim                     $5a9
#cmd dx_mv1_set_attach_anim_time            $5aa
#cmd dx_mv1_set_attach_anim_blend_rate      $5ab
#cmd dx_mv1_set_attach_anim_blend_rate_to_frame $5ac
#cmd dx_mv1_set_attach_anim_time_to_frame   $5ad
#cmd dx_mv1_get_attach_anim                 $5ae
#cmd dx_mv1_set_attach_anim_use_shape_flag  $5af
#cmd dx_mv1_get_attach_anim_use_shape_flag  $5b0
#cmd dx_mv1_get_anim_num                    $5b1
#cmd dx_mv1_set_anim_name                   $5b2
#cmd dx_mv1_get_anim_index                  $5b3
#cmd dx_mv1_get_anim_target_frame_num       $5b4
#cmd dx_mv1_get_anim_target_frame           $5b5
#cmd dx_mv1_get_anim_target_frame_key_set_num $5b6
#cmd dx_mv1_get_anim_target_frame_key_set   $5b7
#cmd dx_mv1_get_anim_key_set_num            $5b8
#cmd dx_mv1_get_anim_key_set_type           $5b9
#cmd dx_mv1_get_anim_key_set_data_type      $5ba
#cmd dx_mv1_get_anim_key_set_time_type      $5bb
#cmd dx_mv1_get_anim_key_set_data_num       $5bc
#cmd dx_mv1_get_anim_key_data_index_from_time $5bd
#cmd dx_mv1_get_material_num                $5be
#cmd dx_mv1_set_material_type_all           $5bf
#cmd dx_mv1_set_material_type               $5c0
#cmd dx_mv1_get_material_type               $5c1
#cmd dx_mv1_set_material_dif_color          $5c2
#cmd dx_mv1_set_material_spc_color          $5c3
#cmd dx_mv1_set_material_emi_color          $5c4
#cmd dx_mv1_set_material_amb_color          $5c5
#cmd dx_mv1_set_material_spc_power          $5c6
#cmd dx_mv1_set_material_dif_map_texture    $5c7
#cmd dx_mv1_get_material_dif_map_texture    $5c8
#cmd dx_mv1_set_material_sub_dif_map_texture $5c9
#cmd dx_mv1_get_material_sub_dif_map_texture $5ca
#cmd dx_mv1_set_material_spc_map_texture    $5cb
#cmd dx_mv1_get_material_spc_map_texture    $5cc
#cmd dx_mv1_set_material_normal_map_texture $5cd
#cmd dx_mv1_get_material_normal_map_texture $5ce
#cmd dx_mv1_set_material_dif_grad_texture   $5cf
#cmd dx_mv1_get_material_dif_grad_texture   $5d0
#cmd dx_mv1_set_material_spc_grad_texture   $5d1
#cmd dx_mv1_get_material_spc_grad_texture   $5d2
#cmd dx_mv1_set_material_sphere_map_texture $5d3
#cmd dx_mv1_get_material_sphere_map_texture $5d4
#cmd dx_mv1_set_material_dif_grad_blend_type_all $5d5
#cmd dx_mv1_set_material_dif_grad_blend_type $5d6
#cmd dx_mv1_get_material_dif_grad_blend_type $5d7
#cmd dx_mv1_set_material_spc_grad_blend_type_all $5d8
#cmd dx_mv1_set_material_spc_grad_blend_type $5d9
#cmd dx_mv1_get_material_spc_grad_blend_type $5da
#cmd dx_mv1_set_material_sphere_map_blend_type_all $5db
#cmd dx_mv1_set_material_sphere_map_blend_type $5dc
#cmd dx_mv1_get_material_sphere_map_blend_type $5dd
#cmd dx_mv1_set_material_out_line_width_all $5de
#cmd dx_mv1_set_material_out_line_width     $5df
#cmd dx_mv1_set_material_out_line_dot_width_all $5e0
#cmd dx_mv1_set_material_out_line_dot_width $5e1
#cmd dx_mv1_set_material_out_line_color_all $5e2
#cmd dx_mv1_set_material_out_line_color     $5e3
#cmd dx_mv1_set_material_draw_blend_mode_all $5e4
#cmd dx_mv1_set_material_draw_blend_mode    $5e5
#cmd dx_mv1_get_material_draw_blend_mode    $5e6
#cmd dx_mv1_set_material_draw_blend_param_all $5e7
#cmd dx_mv1_set_material_draw_blend_param   $5e8
#cmd dx_mv1_get_material_draw_blend_param   $5e9
#cmd dx_mv1_set_material_draw_alpha_test_all $5ea
#cmd dx_mv1_set_material_draw_alpha_test    $5eb
#cmd dx_mv1_get_material_draw_alpha_test_enable $5ec
#cmd dx_mv1_get_material_draw_alpha_test_mode $5ed
#cmd dx_mv1_get_material_draw_alpha_test_param $5ee
#cmd dx_mv1_set_material_draw_add_color_all $5ef
#cmd dx_mv1_set_material_draw_add_color     $5f0
#cmd dx_mv1_get_texture_num                 $5f1
#cmd dx_mv1_set_texture_color_file_path     $5f2
#cmd dx_mv1_set_texture_alpha_file_path     $5f3
#cmd dx_mv1_set_texture_graph_handle        $5f4
#cmd dx_mv1_get_texture_graph_handle        $5f5
#cmd dx_mv1_set_texture_address_mode        $5f6
#cmd dx_mv1_get_texture_address_mode_u      $5f7
#cmd dx_mv1_get_texture_address_mode_v      $5f8
#cmd dx_mv1_get_texture_width               $5f9
#cmd dx_mv1_get_texture_height              $5fa
#cmd dx_mv1_get_texture_semi_trans_state    $5fb
#cmd dx_mv1_set_texture_bump_image_flag     $5fc
#cmd dx_mv1_get_texture_bump_image_flag     $5fd
#cmd dx_mv1_set_texture_bump_image_next_pixel_length $5fe
#cmd dx_mv1_set_texture_sample_filter_mode  $5ff
#cmd dx_mv1_get_texture_sample_filter_mode  $600
#cmd dx_mv1_add_texture_graph_handle        $601
#cmd dx_mv1_load_texture                    $602
#cmd dx_mv1_get_frame_num                   $603
#cmd dx_mv1_search_frame                    $604
#cmd dx_mv1_search_frame_child              $605
#cmd dx_mv1_get_frame_name2                 $606
#cmd dx_mv1_get_frame_parent                $607
#cmd dx_mv1_get_frame_child_num             $608
#cmd dx_mv1_get_frame_child                 $609
#cmd dx_mv1_set_frame_user_local_matrix     $60a
#cmd dx_mv1_set_frame_user_local_matrix_d   $60b
#cmd dx_mv1_reset_frame_user_local_matrix   $60c
#cmd dx_mv1_set_frame_user_local_world_matrix $60d
#cmd dx_mv1_set_frame_user_local_world_matrix_d $60e
#cmd dx_mv1_reset_frame_user_local_world_matrix $60f
#cmd dx_mv1_get_frame_vertex_num            $610
#cmd dx_mv1_get_frame_triangle_num          $611
#cmd dx_mv1_get_frame_mesh_num              $612
#cmd dx_mv1_get_frame_mesh                  $613
#cmd dx_mv1_set_frame_visible               $614
#cmd dx_mv1_get_frame_visible               $615
#cmd dx_mv1_set_frame_dif_color_scale       $616
#cmd dx_mv1_set_frame_spc_color_scale       $617
#cmd dx_mv1_set_frame_emi_color_scale       $618
#cmd dx_mv1_set_frame_amb_color_scale       $619
#cmd dx_mv1_get_frame_semi_trans_state      $61a
#cmd dx_mv1_set_frame_opacity_rate          $61b
#cmd dx_mv1_set_frame_base_visible          $61c
#cmd dx_mv1_get_frame_base_visible          $61d
#cmd dx_mv1_set_frame_texture_address_transform $61e
#cmd dx_mv1_set_frame_texture_address_transform_matrix $61f
#cmd dx_mv1_reset_frame_texture_address_transform $620
#cmd dx_mv1_get_mesh_num                    $621
#cmd dx_mv1_get_mesh_material               $622
#cmd dx_mv1_get_mesh_vertex_num             $623
#cmd dx_mv1_get_mesh_triangle_num           $624
#cmd dx_mv1_set_mesh_visible                $625
#cmd dx_mv1_get_mesh_visible                $626
#cmd dx_mv1_set_mesh_dif_color_scale        $627
#cmd dx_mv1_set_mesh_spc_color_scale        $628
#cmd dx_mv1_set_mesh_emi_color_scale        $629
#cmd dx_mv1_set_mesh_amb_color_scale        $62a
#cmd dx_mv1_set_mesh_opacity_rate           $62b
#cmd dx_mv1_set_mesh_draw_blend_mode        $62c
#cmd dx_mv1_set_mesh_draw_blend_param       $62d
#cmd dx_mv1_get_mesh_draw_blend_mode        $62e
#cmd dx_mv1_get_mesh_draw_blend_param       $62f
#cmd dx_mv1_set_mesh_base_visible           $630
#cmd dx_mv1_get_mesh_base_visible           $631
#cmd dx_mv1_set_mesh_back_culling           $632
#cmd dx_mv1_get_mesh_back_culling           $633
#cmd dx_mv1_get_mesh_t_list_num             $634
#cmd dx_mv1_get_mesh_t_list                 $635
#cmd dx_mv1_get_mesh_semi_trans_state       $636
#cmd dx_mv1_set_mesh_use_vert_dif_color     $637
#cmd dx_mv1_set_mesh_use_vert_spc_color     $638
#cmd dx_mv1_get_mesh_use_vert_dif_color     $639
#cmd dx_mv1_get_mesh_use_vert_spc_color     $63a
#cmd dx_mv1_get_mesh_shape_flag             $63b
#cmd dx_mv1_get_shape_num                   $63c
#cmd dx_mv1_search_shape                    $63d
#cmd dx_mv1_get_shape_target_mesh_num       $63e
#cmd dx_mv1_get_shape_target_mesh           $63f
#cmd dx_mv1_set_shape_rate                  $640
#cmd dx_mv1_get_triangle_list_num           $641
#cmd dx_mv1_get_triangle_list_vertex_type   $642
#cmd dx_mv1_get_triangle_list_polygon_num   $643
#cmd dx_mv1_get_triangle_list_vertex_num    $644
#cmd dx_mv1_get_triangle_list_local_world_matrix_num $645
#cmd dx_mv1_get_triangle_list_use_material  $646
#cmd dx_mv1_setup_coll_info                 $647
#cmd dx_mv1_terminate_coll_info             $648
#cmd dx_mv1_refresh_coll_info               $649
#cmd dx_mv1_setup_reference_mesh            $64a
#cmd dx_mv1_terminate_reference_mesh        $64b
#cmd dx_mv1_refresh_reference_mesh          $64c
#cmd dx_live2_d_set_cubism4_core_dll_path   $64d
#cmd dx_live2_d_set_cubism3_core_dll_path   $64e
#cmd dx_live2_d_render_begin                $64f
#cmd dx_live2_d_render_end                  $650
#cmd dx_live2_d_load_model                  $651
#cmd dx_live2_d_delete_model                $652
#cmd dx_live2_d_init_model                  $653
#cmd dx_live2_d_set_use_auto_scaling        $654
#cmd dx_live2_d_set_use_auto_centering      $655
#cmd dx_live2_d_set_use_reverse_y_axis      $656
#cmd dx_live2_d_model_update                $657
#cmd dx_live2_d_model_set_translate         $658
#cmd dx_live2_d_model_set_extend_rate       $659
#cmd dx_live2_d_model_set_rotate            $65a
#cmd dx_live2_d_model_draw                  $65b
#cmd dx_live2_d_model_start_motion          $65c
#cmd dx_live2_d_model_get_last_play_motion_no $65d
#cmd dx_live2_d_model_is_motion_finished    $65e
#cmd dx_live2_d_model_set_expression        $65f
#cmd dx_live2_d_model_hit_test              $660
#cmd dx_live2_d_model_get_parameter_count   $661
#cmd dx_live2_d_model_set_parameter_value   $662
#cmd dx_live2_d_model_get_hit_areas_count   $663
#cmd dx_live2_d_model_get_expression_count  $664
#cmd dx_live2_d_model_get_motion_group_count $665
#cmd dx_live2_d_model_get_motion_count      $666
#cmd dx_live2_d_model_get_eye_blink_parameter_count $667
#cmd dx_live2_d_model_get_lip_sync_parameter_count $668

#endif