;============================================================
;  iron_dxlib_auto.as — Phase 5.3 自動生成 DxLib bindings
;  DO NOT EDIT — tools/hsp3dx_dxlib_gen/gen_dxlib_bindings.py で再生成
;  関数数: 512
;============================================================
#ifndef __iron_dxlib_auto_as__
#define __iron_dxlib_auto_as__

#regcmd 9

#cmd dx_global_struct_initialize            $200
#cmd dx_is_init                             $201
#cmd dx_get_last_error_code                 $202
#cmd dx_get_last_error_message              $203
#cmd dx_set_always_run_flag                 $204
#cmd dx_wait_timer                          $205
#cmd dx_wait_key                            $206
#cmd dx_sleep_thread                        $207
#cmd dx_get_now_count                       $208
#cmd dx_get_rand                            $209
#cmd dx_s_rand                              $20a
#cmd dx_get_battery_life_percent            $20b
#cmd dx_get_clipboard_text                  $20c
#cmd dx_set_clipboard_text                  $20d
#cmd dx_log_file_add                        $20e
#cmd dx_log_file_tab_add                    $20f
#cmd dx_log_file_tab_sub                    $210
#cmd dx_error_log_add                       $211
#cmd dx_error_log_tab_add                   $212
#cmd dx_error_log_tab_sub                   $213
#cmd dx_set_use_time_stamp_flag             $214
#cmd dx_set_out_application_log_valid_flag  $215
#cmd dx_set_out_application_system_log_valid_flag $216
#cmd dx_set_application_log_file_name       $217
#cmd dx_set_application_log_save_directory  $218
#cmd dx_set_use_date_name_log_file          $219
#cmd dx_set_log_draw_out_flag               $21a
#cmd dx_get_log_draw_flag                   $21b
#cmd dx_set_log_font_size                   $21c
#cmd dx_set_log_font_handle                 $21d
#cmd dx_set_log_draw_area                   $21e
#cmd dx_puts_dx                             $21f
#cmd dx_cls_dx                              $220
#cmd dx_set_print_color_dx                  $221
#cmd dx_set_use_a_sync_load_flag            $222
#cmd dx_get_use_a_sync_load_flag            $223
#cmd dx_check_handle_a_sync_load            $224
#cmd dx_get_handle_a_sync_load_result       $225
#cmd dx_set_a_sync_load_finish_delete_flag  $226
#cmd dx_wait_handle_a_sync_load             $227
#cmd dx_wait_handle_a_sync_load_all         $228
#cmd dx_get_a_sync_load_num                 $229
#cmd dx_set_a_sync_load_thread_num          $22a
#cmd dx_set_mouse_disp_flag                 $22b
#cmd dx_set_mouse_disp_ignore_menu_flag     $22c
#cmd dx_get_mouse_wheel_rot_vol             $22d
#cmd dx_get_mouse_h_wheel_rot_vol           $22e
#cmd dx_get_touch_input_num                 $22f
#cmd dx_get_touch_input_log_num             $230
#cmd dx_clear_touch_input_log               $231
#cmd dx_get_touch_input_down_log_num        $232
#cmd dx_clear_touch_input_down_log          $233
#cmd dx_get_touch_input_up_log_num          $234
#cmd dx_clear_touch_input_up_log            $235
#cmd dx_dx_set_alloc_print_flag             $236
#cmd dx_dx_get_alloc_num                    $237
#cmd dx_dx_error_check_alloc                $238
#cmd dx_dx_set_alloc_size_out_flag          $239
#cmd dx_dx_set_alloc_memory_error_check_flag $23a
#cmd dx_get_use_char_code_format            $23b
#cmd dx_get_wchar_t_char_code_format        $23c
#cmd dx_strcmp_dx                           $23d
#cmd dx_stricmp_dx                          $23e
#cmd dx_strncmp_dx                          $23f
#cmd dx_strncmp2_dx                         $240
#cmd dx_strpncmp_dx                         $241
#cmd dx_strpncmp2_dx                        $242
#cmd dx_strstr2_dx                          $243
#cmd dx_strrstr2_dx                         $244
#cmd dx_atoi_dx                             $245
#cmd dx_process_net_message                 $246
#cmd dx_preparation_listen_net_work         $247
#cmd dx_preparation_listen_net_work_i_pv6   $248
#cmd dx_stop_listen_net_work                $249
#cmd dx_close_net_work                      $24a
#cmd dx_get_net_work_accept_state           $24b
#cmd dx_get_net_work_data_length            $24c
#cmd dx_get_net_work_send_data_length       $24d
#cmd dx_get_new_accept_net_work             $24e
#cmd dx_get_lost_net_work                   $24f
#cmd dx_set_connect_time_out_wait           $250
#cmd dx_set_use_dx_net_work_protocol        $251
#cmd dx_get_use_dx_net_work_protocol        $252
#cmd dx_set_use_dx_protocol                 $253
#cmd dx_get_use_dx_protocol                 $254
#cmd dx_set_net_work_close_after_lost_flag  $255
#cmd dx_get_net_work_close_after_lost_flag  $256
#cmd dx_net_work_recv_buffer_clear          $257
#cmd dx_make_udp_socket                     $258
#cmd dx_make_udp_socket_i_pv6               $259
#cmd dx_delete_udp_socket                   $25a
#cmd dx_check_net_work_recv_udp             $25b
#cmd dx_clear_input_char_buf                $25c
#cmd dx_get_one_char                        $25d
#cmd dx_get_one_char_wait                   $25e
#cmd dx_draw_ime_input_string               $25f
#cmd dx_draw_ime_input_extend_string        $260
#cmd dx_set_use_ime_flag                    $261
#cmd dx_get_use_ime_flag                    $262
#cmd dx_set_input_string_max_length_ime_sync $263
#cmd dx_set_ime_input_string_max_length     $264
#cmd dx_get_string_point                    $265
#cmd dx_get_string_point2                   $266
#cmd dx_get_string_length                   $267
#cmd dx_key_input_number                    $268
#cmd dx_get_ime_input_mode_str              $269
#cmd dx_set_ime_input_string                $26a
#cmd dx_set_key_input_string_font           $26b
#cmd dx_draw_key_input_mode_string          $26c
#cmd dx_init_key_input                      $26d
#cmd dx_delete_key_input                    $26e
#cmd dx_set_active_key_input                $26f
#cmd dx_get_active_key_input                $270
#cmd dx_check_key_input                     $271
#cmd dx_re_start_key_input                  $272
#cmd dx_process_act_key_input               $273
#cmd dx_draw_key_input_string               $274
#cmd dx_draw_key_input_extend_string        $275
#cmd dx_set_key_input_draw_area             $276
#cmd dx_set_key_input_select_area           $277
#cmd dx_set_key_input_draw_start_pos        $278
#cmd dx_get_key_input_draw_start_pos        $279
#cmd dx_set_key_input_cursor_brink_time     $27a
#cmd dx_set_key_input_cursor_brink_flag     $27b
#cmd dx_set_key_input_string                $27c
#cmd dx_set_key_input_number                $27d
#cmd dx_set_key_input_number_to_float       $27e
#cmd dx_get_key_input_string                $27f
#cmd dx_get_key_input_number                $280
#cmd dx_set_key_input_cursor_position       $281
#cmd dx_get_key_input_cursor_position       $282
#cmd dx_file_read_open                      $283
#cmd dx_file_read_close                     $284
#cmd dx_file_read_idle_chk                  $285
#cmd dx_file_read_eof                       $286
#cmd dx_file_read_gets                      $287
#cmd dx_file_read_fully_load                $288
#cmd dx_file_read_fully_load_delete         $289
#cmd dx_get_stream_function_default         $28a
#cmd dx_convert_full_path                   $28b
#cmd dx_check_hit_key_all                   $28c
#cmd dx_get_joypad_num                      $28d
#cmd dx_get_joypad_button_num               $28e
#cmd dx_check_joypad_x_input                $28f
#cmd dx_get_joypad_type                     $290
#cmd dx_set_joypad_input_to_key_input       $291
#cmd dx_set_joypad_dead_zone                $292
#cmd dx_set_joypad_default_dead_zone_all    $293
#cmd dx_start_joypad_vibration              $294
#cmd dx_stop_joypad_vibration               $295
#cmd dx_get_joypad_pov_state                $296
#cmd dx_re_setup_joypad                     $297
#cmd dx_re_setup_input_system               $298
#cmd dx_set_use_joypad_vibration_flag       $299
#cmd dx_make_graph                          $29a
#cmd dx_derivation_graph                    $29b
#cmd dx_derivation_graph_f                  $29c
#cmd dx_delete_sharing_graph                $29d
#cmd dx_get_graph_num                       $29e
#cmd dx_fill_graph                          $29f
#cmd dx_fill_rect_graph                     $2a0
#cmd dx_init_graph                          $2a1
#cmd dx_reload_file_graph_all               $2a2
#cmd dx_make_shadow_map                     $2a3
#cmd dx_delete_shadow_map                   $2a4
#cmd dx_shadow_map_draw_setup               $2a5
#cmd dx_shadow_map_draw_end                 $2a6
#cmd dx_set_use_shadow_map                  $2a7
#cmd dx_reset_shadow_map_draw_area          $2a8
#cmd dx_set_shadow_map_adjust_depth         $2a9
#cmd dx_test_draw_shadow_map                $2aa
#cmd dx_load_bmp_to_graph                   $2ab
#cmd dx_load_reverse_graph                  $2ac
#cmd dx_load_blend_graph                    $2ad
#cmd dx_create_blend_graph_from_soft_image  $2ae
#cmd dx_create_graph_from_soft_image        $2af
#cmd dx_create_graph_from_rect_soft_image   $2b0
#cmd dx_re_create_graph_from_soft_image     $2b1
#cmd dx_re_create_graph_from_rect_soft_image $2b2
#cmd dx_reload_graph                        $2b3
#cmd dx_reload_reverse_graph                $2b4
#cmd dx_set_graph_color_bit_depth           $2b5
#cmd dx_get_graph_color_bit_depth           $2b6
#cmd dx_set_create_graph_color_bit_depth    $2b7
#cmd dx_get_create_graph_color_bit_depth    $2b8
#cmd dx_set_create_graph_channel_bit_depth  $2b9
#cmd dx_get_create_graph_channel_bit_depth  $2ba
#cmd dx_set_create_graph_init_graph_delete  $2bb
#cmd dx_get_create_graph_init_graph_delete  $2bc
#cmd dx_set_create_graph_handle             $2bd
#cmd dx_get_create_graph_handle             $2be
#cmd dx_set_draw_valid_graph_create_flag    $2bf
#cmd dx_get_draw_valid_graph_create_flag    $2c0
#cmd dx_set_draw_valid_flag_of3_d_graph     $2c1
#cmd dx_set_left_up_color_is_trans_color_flag $2c2
#cmd dx_set_use_palette_graph_flag          $2c3
#cmd dx_set_use_blend_graph_create_flag     $2c4
#cmd dx_get_use_blend_graph_create_flag     $2c5
#cmd dx_set_use_alpha_test_graph_create_flag $2c6
#cmd dx_get_use_alpha_test_graph_create_flag $2c7
#cmd dx_set_use_alpha_test_flag             $2c8
#cmd dx_get_use_alpha_test_flag             $2c9
#cmd dx_set_cube_map_texture_create_flag    $2ca
#cmd dx_get_cube_map_texture_create_flag    $2cb
#cmd dx_set_use_no_blend_mode_param         $2cc
#cmd dx_set_draw_valid_alpha_channel_graph_create_flag $2cd
#cmd dx_get_draw_valid_alpha_channel_graph_create_flag $2ce
#cmd dx_set_draw_valid_float_type_graph_create_flag $2cf
#cmd dx_get_draw_valid_float_type_graph_create_flag $2d0
#cmd dx_set_draw_valid_graph_create_z_buffer_flag $2d1
#cmd dx_get_draw_valid_graph_create_z_buffer_flag $2d2
#cmd dx_set_create_draw_valid_graph_z_buffer_bit_depth $2d3
#cmd dx_get_create_draw_valid_graph_z_buffer_bit_depth $2d4
#cmd dx_set_create_draw_valid_graph_mip_levels $2d5
#cmd dx_get_create_draw_valid_graph_mip_levels $2d6
#cmd dx_set_create_draw_valid_graph_channel_num $2d7
#cmd dx_get_create_draw_valid_graph_channel_num $2d8
#cmd dx_set_create_draw_valid_graph_multi_sample $2d9
#cmd dx_set_draw_valid_multi_sample         $2da
#cmd dx_get_multi_sample_quality            $2db
#cmd dx_set_use_trans_color                 $2dc
#cmd dx_set_use_trans_color_graph_create_flag $2dd
#cmd dx_set_use_graph_alpha_channel         $2de
#cmd dx_get_use_graph_alpha_channel         $2df
#cmd dx_set_use_alpha_channel_graph_create_flag $2e0
#cmd dx_get_use_alpha_channel_graph_create_flag $2e1
#cmd dx_set_use_not_manage_texture_flag     $2e2
#cmd dx_get_use_not_manage_texture_flag     $2e3
#cmd dx_set_use_platform_texture_format     $2e4
#cmd dx_get_use_platform_texture_format     $2e5
#cmd dx_set_trans_color                     $2e6
#cmd dx_set_use_div_graph_flag              $2e7
#cmd dx_set_use_alpha_image_load_flag       $2e8
#cmd dx_set_use_max_texture_size            $2e9
#cmd dx_set_use_graph_base_data_backup      $2ea
#cmd dx_get_use_graph_base_data_backup      $2eb
#cmd dx_set_use_system_mem_graph_create_flag $2ec
#cmd dx_get_use_system_mem_graph_create_flag $2ed
#cmd dx_set_use_load_div_graph_size_check_flag $2ee
#cmd dx_get_use_load_div_graph_size_check_flag $2ef
#cmd dx_graph_un_lock                       $2f0
#cmd dx_set_use_graph_z_buffer              $2f1
#cmd dx_copy_graph_z_buffer_image           $2f2
#cmd dx_set_device_lost_delete_graph_flag   $2f3
#cmd dx_get_graph_mipmap_count              $2f4
#cmd dx_get_graph_file_path                 $2f5
#cmd dx_check_draw_valid_graph              $2f6
#cmd dx_get_valid_restore_shred_point       $2f7
#cmd dx_reset_graph_palette                 $2f8
#cmd dx_begin_aa_draw                       $2f9
#cmd dx_end_aa_draw                         $2fa
#cmd dx_load_graph_screen                   $2fb
#cmd dx_draw_rota_graph2                    $2fc
#cmd dx_draw_rota_graph3                    $2fd
#cmd dx_draw_rota_graph_fast                $2fe
#cmd dx_draw_rota_graph_fast2               $2ff
#cmd dx_draw_rota_graph_fast3               $300
#cmd dx_draw_turn_graph                     $301
#cmd dx_draw_reverse_graph                  $302
#cmd dx_draw_graph_f                        $303
#cmd dx_draw_extend_graph_f                 $304
#cmd dx_draw_rota_graph_f                   $305
#cmd dx_draw_rota_graph2_f                  $306
#cmd dx_draw_rota_graph3_f                  $307
#cmd dx_draw_rota_graph_fast_f              $308
#cmd dx_draw_rota_graph_fast2_f             $309
#cmd dx_draw_rota_graph_fast3_f             $30a
#cmd dx_draw_modi_graph_f                   $30b
#cmd dx_draw_turn_graph_f                   $30c
#cmd dx_draw_reverse_graph_f                $30d
#cmd dx_draw_tile                           $30e
#cmd dx_draw_rect_extend_graph              $30f
#cmd dx_draw_rect_rota_graph2               $310
#cmd dx_draw_rect_rota_graph3               $311
#cmd dx_draw_rect_rota_graph_fast           $312
#cmd dx_draw_rect_rota_graph_fast2          $313
#cmd dx_draw_rect_rota_graph_fast3          $314
#cmd dx_draw_rect_modi_graph                $315
#cmd dx_draw_rect_graph_f                   $316
#cmd dx_draw_rect_graph_f2                  $317
#cmd dx_draw_rect_extend_graph_f            $318
#cmd dx_draw_rect_extend_graph_f2           $319
#cmd dx_draw_rect_rota_graph_f              $31a
#cmd dx_draw_rect_rota_graph2_f             $31b
#cmd dx_draw_rect_rota_graph3_f             $31c
#cmd dx_draw_rect_rota_graph_fast_f         $31d
#cmd dx_draw_rect_rota_graph_fast2_f        $31e
#cmd dx_draw_rect_rota_graph_fast3_f        $31f
#cmd dx_draw_rect_modi_graph_f              $320
#cmd dx_draw_blend_graph                    $321
#cmd dx_draw_blend_graph_f                  $322
#cmd dx_draw_blend_graph_pos                $323
#cmd dx_draw_circle_gauge                   $324
#cmd dx_draw_circle_gauge_f                 $325
#cmd dx_draw_polygon3_d_use_vertex_buffer   $326
#cmd dx_draw_polygon_indexed3_d_use_vertex_buffer $327
#cmd dx_draw_graph3_d                       $328
#cmd dx_draw_extend_graph3_d                $329
#cmd dx_draw_rota_graph3_d                  $32a
#cmd dx_draw_rota2_graph3_d                 $32b
#cmd dx_get_draw_mode                       $32c
#cmd dx_set_draw_alpha_test                 $32d
#cmd dx_set_blend_graph                     $32e
#cmd dx_set_blend_graph_position            $32f
#cmd dx_set_draw_add_color                  $330
#cmd dx_set_write_alpha_channel_flag        $331
#cmd dx_get_write_alpha_channel_flag        $332
#cmd dx_check_separate_alpha_blend_enable   $333
#cmd dx_set_ignore_draw_graph_color         $334
#cmd dx_get_ignore_draw_graph_color         $335
#cmd dx_set_max_anisotropy                  $336
#cmd dx_get_max_anisotropy                  $337
#cmd dx_set_use_large3_d_position_support   $338
#cmd dx_set_use_z_buffer_flag               $339
#cmd dx_set_write_z_buffer_flag             $33a
#cmd dx_set_z_bias                          $33b
#cmd dx_set_z_bias3_d                       $33c
#cmd dx_set_draw_z                          $33d
#cmd dx_set_use_reversed_z                  $33e
#cmd dx_set_draw_area                       $33f
#cmd dx_set_draw_area_full                  $340
#cmd dx_set_draw3_d_scale                   $341
#cmd dx_run_restore_shred                   $342
#cmd dx_reset_transform_to2_d               $343
#cmd dx_set_def_transform_matrix            $344
#cmd dx_set_use_culling_flag                $345
#cmd dx_get_use_back_culling                $346
#cmd dx_set_use_right_hand_clipping_process $347
#cmd dx_get_use_right_hand_clipping_process $348
#cmd dx_set_texture_address_mode_uv         $349
#cmd dx_set_texture_address_transform       $34a
#cmd dx_reset_texture_address_transform     $34b
#cmd dx_set_fog_enable                      $34c
#cmd dx_get_fog_enable                      $34d
#cmd dx_get_fog_mode                        $34e
#cmd dx_set_fog_color                       $34f
#cmd dx_set_fog_start_end                   $350
#cmd dx_set_fog_density                     $351
#cmd dx_set_vertical_fog_enable             $352
#cmd dx_get_vertical_fog_enable             $353
#cmd dx_get_vertical_fog_mode               $354
#cmd dx_set_vertical_fog_color              $355
#cmd dx_set_vertical_fog_start_end          $356
#cmd dx_set_vertical_fog_density            $357
#cmd dx_get_draw_screen_graph               $358
#cmd dx_blt_draw_valid_graph                $359
#cmd dx_screen_copy                         $35a
#cmd dx_wait_v_sync                         $35b
#cmd dx_cls_draw_screen                     $35c
#cmd dx_get_draw_screen                     $35d
#cmd dx_get_active_graph                    $35e
#cmd dx_set_use_set_draw_screen_setting_reset $35f
#cmd dx_get_use_set_draw_screen_setting_reset $360
#cmd dx_set_draw_z_buffer                   $361
#cmd dx_get_use_full_screen_resolution_mode $362
#cmd dx_set_emulation320x240                $363
#cmd dx_set_z_buffer_size                   $364
#cmd dx_set_z_buffer_bit_depth              $365
#cmd dx_get_wait_v_sync_flag                $366
#cmd dx_set_full_scene_anti_aliasing_mode   $367
#cmd dx_set_graph_display_area              $368
#cmd dx_set_change_screen_mode_graphics_system_reset_flag $369
#cmd dx_get_screen_bit_depth                $36a
#cmd dx_get_color_bit_depth                 $36b
#cmd dx_get_change_display_flag             $36c
#cmd dx_get_refresh_rate                    $36d
#cmd dx_get_display_num                     $36e
#cmd dx_get_display_mode_num                $36f
#cmd dx_get_multi_draw_screen_num           $370
#cmd dx_get_draw_float_coord_type           $371
#cmd dx_set_use_normal_draw_shader          $372
#cmd dx_set_use_software_render_mode_flag   $373
#cmd dx_set_not_use3_d_flag                 $374
#cmd dx_set_use3_d_flag                     $375
#cmd dx_get_use3_d_flag                     $376
#cmd dx_set_screen_mem_to_vram_flag         $377
#cmd dx_get_screen_mem_to_system_mem_flag   $378
#cmd dx_restore_graph_system                $379
#cmd dx_set_use_hardware_vertex_processing  $37a
#cmd dx_set_use_pixel_lighting              $37b
#cmd dx_set_use_old_draw_modi_graph_code_flag $37c
#cmd dx_set_use_vram_flag                   $37d
#cmd dx_get_use_vram_flag                   $37e
#cmd dx_set_basic_blend_flag                $37f
#cmd dx_set_use_basic_graph_draw3_d_device_method_flag $380
#cmd dx_set_use_display_index               $381
#cmd dx_render_vertex                       $382
#cmd dx_get_draw_call_count                 $383
#cmd dx_save_draw_screen_to_bmp             $384
#cmd dx_save_draw_screen_to_dds             $385
#cmd dx_save_draw_screen_to_jpeg            $386
#cmd dx_save_draw_screen_to_png             $387
#cmd dx_save_draw_valid_graph               $388
#cmd dx_save_draw_valid_graph_to_bmp        $389
#cmd dx_save_draw_valid_graph_to_dds        $38a
#cmd dx_save_draw_valid_graph_to_jpeg       $38b
#cmd dx_save_draw_valid_graph_to_png        $38c
#cmd dx_delete_vertex_buffer                $38d
#cmd dx_init_vertex_buffer                  $38e
#cmd dx_update_vertex_buffer                $38f
#cmd dx_delete_index_buffer                 $390
#cmd dx_init_index_buffer                   $391
#cmd dx_update_index_buffer                 $392
#cmd dx_get_max_primitive_count             $393
#cmd dx_get_max_vertex_index                $394
#cmd dx_get_valid_shader_version            $395
#cmd dx_load_vertex_shader                  $396
#cmd dx_load_geometry_shader                $397
#cmd dx_load_pixel_shader                   $398
#cmd dx_delete_shader                       $399
#cmd dx_init_shader                         $39a
#cmd dx_get_const_index_to_shader           $39b
#cmd dx_get_const_count_to_shader           $39c
#cmd dx_set_vs_const_sf                     $39d
#cmd dx_set_vs_const_si                     $39e
#cmd dx_reset_vs_const_f                    $39f
#cmd dx_reset_vs_const_i                    $3a0
#cmd dx_reset_vs_const_b                    $3a1
#cmd dx_set_ps_const_sf                     $3a2
#cmd dx_set_ps_const_si                     $3a3
#cmd dx_reset_ps_const_f                    $3a4
#cmd dx_reset_ps_const_i                    $3a5
#cmd dx_reset_ps_const_b                    $3a6
#cmd dx_set_render_target_to_shader         $3a7
#cmd dx_set_use_texture_to_shader           $3a8
#cmd dx_set_use_vertex_shader               $3a9
#cmd dx_set_use_geometry_shader             $3aa
#cmd dx_set_use_pixel_shader                $3ab
#cmd dx_draw_polygon3_d_to_shader_use_vertex_buffer $3ac
#cmd dx_draw_polygon_indexed3_d_to_shader_use_vertex_buffer $3ad
#cmd dx_init_shader_constant_buffer         $3ae
#cmd dx_create_shader_constant_buffer       $3af
#cmd dx_delete_shader_constant_buffer       $3b0
#cmd dx_update_shader_constant_buffer       $3b1
#cmd dx_set_graph_blend_scaling_filter_mode $3b2
#cmd dx_play_movie                          $3b3
#cmd dx_open_movie_to_graph                 $3b4
#cmd dx_seek_movie_to_graph                 $3b5
#cmd dx_set_play_speed_rate_movie_to_graph  $3b6
#cmd dx_get_movie_state_to_graph            $3b7
#cmd dx_set_movie_volume_to_graph           $3b8
#cmd dx_get_movie_volume_to_graph           $3b9
#cmd dx_change_movie_volume_to_graph        $3ba
#cmd dx_get_movie_volume_to_graph2          $3bb
#cmd dx_get_movie_total_frame_to_graph      $3bc
#cmd dx_tell_movie_to_graph                 $3bd
#cmd dx_tell_movie_to_graph_to_frame        $3be
#cmd dx_seek_movie_to_graph_to_frame        $3bf
#cmd dx_get_last_update_time_movie_to_graph $3c0
#cmd dx_update_movie_to_graph               $3c1
#cmd dx_set_movie_right_image_alpha_flag    $3c2
#cmd dx_set_movie_color_a8_r8_g8_b8_flag    $3c3
#cmd dx_set_movie_use_yuv_format_surface_flag $3c4
#cmd dx_set_camera_near_far                 $3c5
#cmd dx_set_camera_near_far_d               $3c6
#cmd dx_set_camera_screen_center            $3c7
#cmd dx_set_camera_screen_center_d          $3c8
#cmd dx_setup_camera_perspective_d          $3c9
#cmd dx_setup_camera_ortho                  $3ca
#cmd dx_setup_camera_ortho_d                $3cb
#cmd dx_set_camera_dot_aspect               $3cc
#cmd dx_set_camera_dot_aspect_d             $3cd
#cmd dx_set_material_use_vert_dif_color     $3ce
#cmd dx_set_material_use_vert_spc_color     $3cf
#cmd dx_set_use_specular                    $3d0
#cmd dx_set_use_light_angle_attenuation     $3d1
#cmd dx_set_use_half_lambert_lighting       $3d2
#cmd dx_get_light_type                      $3d3
#cmd dx_set_light_enable                    $3d4
#cmd dx_get_light_enable                    $3d5
#cmd dx_set_light_range_atten               $3d6
#cmd dx_set_light_angle                     $3d7
#cmd dx_set_light_use_shadow_map            $3d8
#cmd dx_delete_light_handle                 $3d9
#cmd dx_delete_light_handle_all             $3da
#cmd dx_set_light_type_handle               $3db
#cmd dx_set_light_enable_handle             $3dc
#cmd dx_set_light_range_atten_handle        $3dd
#cmd dx_set_light_angle_handle              $3de
#cmd dx_set_light_use_shadow_map_handle     $3df
#cmd dx_get_light_type_handle               $3e0
#cmd dx_get_light_enable_handle             $3e1
#cmd dx_get_enable_light_handle_num         $3e2
#cmd dx_get_enable_light_handle             $3e3
#cmd dx_create_mask_screen                  $3e4
#cmd dx_delete_mask_screen                  $3e5
#cmd dx_set_use_mask_screen_flag            $3e6
#cmd dx_get_use_mask_screen_flag            $3e7
#cmd dx_fill_mask_screen                    $3e8
#cmd dx_set_mask_screen_graph               $3e9
#cmd dx_init_mask                           $3ea
#cmd dx_make_mask                           $3eb
#cmd dx_delete_mask                         $3ec
#cmd dx_load_mask                           $3ed
#cmd dx_draw_mask                           $3ee
#cmd dx_draw_string_mask                    $3ef
#cmd dx_draw_string_mask_to_handle          $3f0
#cmd dx_draw_fill_mask                      $3f1
#cmd dx_set_mask_reverse_effect_flag        $3f2
#cmd dx_get_mask_screen_data                $3f3
#cmd dx_get_mask_use_flag                   $3f4
#cmd dx_enum_font_name                      $3f5
#cmd dx_init_font_to_handle                 $3f6
#cmd dx_load_font_data_to_handle            $3f7
#cmd dx_set_font_space_to_handle            $3f8
#cmd dx_set_font_line_space_to_handle       $3f9
#cmd dx_delete_font_to_handle               $3fa
#cmd dx_add_font_image_to_handle            $3fb
#cmd dx_sub_font_image_to_handle            $3fc
#cmd dx_add_substitution_font_to_handle     $3fd
#cmd dx_sub_substitution_font_to_handle     $3fe
#cmd dx_change_font_from_handle             $3ff

#endif