; ============================================================
;   Auto-generated by tools/gen_winapi_as.py
;   header: C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0/um/winuser.h
;   dll:    user32.dll
;   注意: 自動生成のため手で編集しても上書きされる可能性あり。
;          intptr / NSTRUCT / wstr 対応 (hsp3net 専用)
; ============================================================

#ifndef __user32_gen_as__
#define __user32_gen_as__

;--- structs ---
#defstruct global tagMSG
    #field intptr hwnd
    #field int message
    #field intptr wParam
    #field intptr lParam
    #field int time
    #field intptr pt
#endstruct

;--- functions ---
#uselib "user32.dll"
; BOOL TranslateMessage(const MSG * lpMsg)
#cfunc TranslateMessage "TranslateMessage" var

; BOOL SetWindowPos(HWND hWnd, HWND hWndInsertAfter, int X, int Y, int cx, int cy, UINT uFlags)
#cfunc SetWindowPos "SetWindowPos" intptr, intptr, int, int, int, int, int

; int GetSystemMetrics(int nIndex)
#cfunc GetSystemMetrics "GetSystemMetrics" int

; BOOL SetForegroundWindow(HWND hWnd)
#cfunc SetForegroundWindow "SetForegroundWindow" intptr

; BOOL IsWindowVisible(HWND hWnd)
#cfunc IsWindowVisible "IsWindowVisible" intptr

; int CreateWindowExW(DWORD dwExStyle, LPCWSTR lpClassName, LPCWSTR lpWindowName, DWORD dwStyle, int X, int Y, int nWidth, int nHeight, HWND hWndParent, HMENU hMenu, HINSTANCE hInstance, LPVOID lpParam)
#cfunc CreateWindowExW "CreateWindowExW" int, wstr, wstr, int, int, int, int, int, intptr, intptr, intptr, intptr

; SHORT GetKeyState(int nVirtKey)
#cfunc GetKeyState "GetKeyState" int

; BOOL GetClientRect(HWND hWnd, LPRECT lpRect)
#cfunc GetClientRect "GetClientRect" intptr, var

; BOOL GetCursorPos(LPPOINT lpPoint)
#cfunc GetCursorPos "GetCursorPos" var

; LRESULT SendMessageW(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam)
#cfunc SendMessageW "SendMessageW" intptr, int, intptr, intptr

; int LoadCursorW(HINSTANCE hInstance, LPCWSTR lpCursorName)
#cfunc LoadCursorW "LoadCursorW" intptr, wstr

; int SetCursor(HCURSOR hCursor)
#cfunc SetCursor "SetCursor" intptr

; SHORT GetAsyncKeyState(int vKey)
#cfunc GetAsyncKeyState "GetAsyncKeyState" int

; int MessageBoxW(HWND hWnd, LPCWSTR lpText, LPCWSTR lpCaption, UINT uType)
#cfunc MessageBoxW "MessageBoxW" intptr, wstr, wstr, int

; BOOL DestroyWindow(HWND hWnd)
#cfunc DestroyWindow "DestroyWindow" intptr

; int GetParent(HWND hWnd)
#cfunc GetParent "GetParent" intptr

; LRESULT DispatchMessageW(const MSG * lpMsg)
#cfunc DispatchMessageW "DispatchMessageW" var

; int GetForegroundWindow()
#cfunc GetForegroundWindow "GetForegroundWindow"

; int SetParent(HWND hWndChild, HWND hWndNewParent)
#cfunc SetParent "SetParent" intptr, intptr

; BOOL UpdateWindow(HWND hWnd)
#cfunc UpdateWindow "UpdateWindow" intptr

; BOOL GetMessageW(LPMSG lpMsg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax)
#cfunc GetMessageW "GetMessageW" var, intptr, int, int

; BOOL MoveWindow(HWND hWnd, int X, int Y, int nWidth, int nHeight, BOOL bRepaint)
#cfunc MoveWindow "MoveWindow" intptr, int, int, int, int, int

; BOOL ShowWindow(HWND hWnd, int nCmdShow)
#cfunc ShowWindow "ShowWindow" intptr, int

; BOOL IsWindow(HWND hWnd)
#cfunc IsWindow "IsWindow" intptr

; BOOL SetCursorPos(int X, int Y)
#cfunc SetCursorPos "SetCursorPos" int, int

; LONG_PTR GetWindowLongPtrW(HWND hWnd, int nIndex)
#cfunc GetWindowLongPtrW "GetWindowLongPtrW" intptr, int

; LONG_PTR SetWindowLongPtrW(HWND hWnd, int nIndex, LONG_PTR dwNewLong)
#cfunc SetWindowLongPtrW "SetWindowLongPtrW" intptr, int, intptr

#endif
